#!/usr/bin/env python3
"""Regenerate packaging version artifacts from app.core.release_meta / constants."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.core import release_meta as meta  # noqa: E402


def _version_tuple(version: str) -> tuple[int, int, int, int]:
    parts = [int(p) for p in re.split(r"[^\d]+", version) if p.isdigit()]
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])  # type: ignore[return-value]


def write_version_txt(path: Path) -> None:
    text = "\n".join(
        [
            meta.APP_PRODUCT,
            f"Version: {meta.APP_VERSION} {meta.APP_CHANNEL}",
            f"Status: {meta.APP_CHANNEL} RELEASE",
            f"Build: {meta.APP_BUILD} / Production / 64-bit",
            f"Publisher: {meta.APP_AUTHOR}",
            f"Product: {meta.APP_PRODUCT}",
            f"Copyright: {meta.APP_COPYRIGHT}",
            f"Architecture: {meta.APP_ARCHITECTURE}",
            f"Database: SQLite 3 (vgrajen) SCHEMA {meta.SCHEMA_VERSION}",
            "Runtime: PySide6 / Python (vgrajen)",
            "Requires: Windows 10 64-bit ali novejši",
            "Does not require: .NET, SQL Server",
            f"Release date: {meta.APP_RELEASE_DATE}",
            f"Publisher URL: {meta.APP_PUBLISHER_URL}",
            f"Support: {meta.APP_SUPPORT_EMAIL}",
            "",
        ]
    )
    path.write_text(text, encoding="utf-8")


def write_version_iss(path: Path) -> None:
    text = "\n".join(
        [
            "; Auto-generated by scripts/sync_release_metadata.py — do not edit by hand.",
            f'#define MyAppName "{meta.APP_PRODUCT}"',
            f'#define MyAppVersion "{meta.APP_VERSION}"',
            f'#define MyAppPublisher "{meta.APP_AUTHOR}"',
            f'#define MyAppExeName "{meta.APP_EXE_NAME}.exe"',
            f'#define MyAppPublisherURL "{meta.APP_PUBLISHER_URL}"',
            f'#define MyAppSupportURL "{meta.APP_SUPPORT_URL}"',
            f'#define MyAppUpdatesURL "{meta.APP_UPDATES_URL}"',
            f'#define MyAppSupportEmail "{meta.APP_SUPPORT_EMAIL}"',
            f'#define MyAppCopyright "{meta.APP_COPYRIGHT}"',
            f'#define MySchemaVersion "{meta.SCHEMA_VERSION}"',
            "",
        ]
    )
    path.write_text(text, encoding="utf-8")


def write_file_version_info(path: Path) -> None:
    major, minor, patch, build = _version_tuple(meta.APP_VERSION)
    text = f"""# UTF-8
#
# Auto-generated by scripts/sync_release_metadata.py — do not edit by hand.
# PyInstaller version resource for {meta.APP_EXE_NAME}.exe
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'{meta.APP_AUTHOR}'),
        StringStruct(u'FileDescription', u'{meta.APP_PRODUCT}'),
        StringStruct(u'FileVersion', u'{meta.APP_VERSION}'),
        StringStruct(u'InternalName', u'{meta.APP_EXE_NAME}'),
        StringStruct(u'LegalCopyright', u'Copyright {meta.APP_COPYRIGHT}'),
        StringStruct(u'OriginalFilename', u'{meta.APP_EXE_NAME}.exe'),
        StringStruct(u'ProductName', u'{meta.APP_PRODUCT}'),
        StringStruct(u'ProductVersion', u'{meta.APP_VERSION}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""
    path.write_text(text, encoding="utf-8")


def main() -> int:
    write_version_txt(ROOT / "Version.txt")
    write_version_txt(ROOT / "packaging" / "Version.txt")
    write_version_iss(ROOT / "packaging" / "version.iss")
    write_file_version_info(ROOT / "packaging" / "file_version_info.txt")
    print(
        f"Synced release metadata: {meta.APP_VERSION} {meta.APP_CHANNEL} "
        f"(schema {meta.SCHEMA_VERSION})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
